backend/apps/adminapp/urls.py
from django.urls import re_path
import backend.apps.adminapp.views as admin

app_name = 'admin'

urlpatterns = [
    re_path(r'^$', admin.index, name='index'),

    re_path(r'^user_list/$', admin.user_list, name='user_list'),
    re_path(r'^user/create/$', admin.user_create, name='user_create'),
    re_path(r'^user/update/(?P<pk>\d+)/$', admin.user_update, name='user_update'),
    re_path(r'^user/delete/(?P<pk>\d+)/$', admin.user_delete, name='user_delete'),

    re_path(r'^category/list/$', admin.category_list, name='category_list'),
    re_path(r'^category/create/$', admin.CategoryCreateView.as_view(), name='category_create'),
    re_path(r'^category/update/(?P<pk>\d+)/$', admin.CategoryUpdateView.as_view(), name='category_update'),
    re_path(r'^category/delete/(?P<pk>\d+)/$', admin.CategoryDeleteView.as_view(), name='category_delete'),
    re_path(r'^category/products/(?P<pk>\d+)/$', admin.category_products, name='category_products'),

    re_path(r'^product/create/(?P<pk>\d+)/$', admin.product_create, name='product_create'),
    re_path(r'^product/read/(?P<pk>\d+)/$', admin.ProductDetailView.as_view(), name='product_read'),
    re_path(r'^product/update/(?P<pk>\d+)/$', admin.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', admin.product_delete, name='product_delete'),
]

backend/apps/authapp/urls.py
from django.urls import re_path
import backend.apps.authapp.views as auth

app_name = 'auth'

urlpatterns = [
    re_path(r'^login/$', auth.login, name='login'),
    re_path(r'^logout/$', auth.logout, name='logout'),
    re_path(r'^register/$', auth.register, name='register'),
    re_path(r'^update/$', auth.update, name='update'),
]

backend/apps/mainapp/urls.py
from django.urls import re_path
import backend.apps.mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.main, name='index'),
    re_path(r'^catalog/$', mainapp.catalog, name='catalog'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^contacts/$', mainapp.contacts, name='contacts'),
]

shop_it_trade/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'^', include('backend.apps.mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('backend.apps.authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('backend.apps.basketapp.urls', namespace='basket')),
    re_path(r'^admin_panel/', include('backend.apps.adminapp.urls', namespace='admin_panel')),
    re_path(r'^order/', include('backend.apps.orderapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/apps/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from backend.apps.adminapp.forms import UserAdminCreateForm, UserAdminUpdateForm, ProductCategoryAdminUpdateForm, \
    ProductAdminUpdateForm
from backend.apps.authapp.models import User
from backend.apps.mainapp.models import ProductCategory, Product


def index(request):
    context = {
        'page_title': 'Админка',
    }
    return render(request, 'adminapp/admin_panel.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_list(request):
    object_list = User.objects.all()[:3]

    context = {
        'page_title': 'Админка/пользователи',
        'object_list': object_list
    }
    return render(request, 'adminapp/user_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_create(request):
    if request.method == 'POST':
        form = UserAdminCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:index'))
    else:
        form = UserAdminCreateForm()

    context = {
        'page_title': 'Админка/новый пользователь',
        'form': form
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_update(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = UserAdminUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:index'))
    else:
        form = UserAdminUpdateForm(instance=user)

    context = {
        'page_title': 'Админка/редактирование пользователя',
        'form': form
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_delete(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin_panel:index'))
    elif request.method == 'GET':
        context = {
            'page_title': 'Админка/удаление пользователя',
            'object': user,
        }
        return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda x: x.is_superuser)
def category_list(request):
    object_list = ProductCategory.objects.all()

    context = {
        'page_title': 'Админка/категории',
        'object_list': object_list,
    }

    return render(request, 'adminapp/category_list.html', context)


class CategoryCreateView(CreateView):
    model = ProductCategory
    success_url = reverse_lazy('admin_panel:category_list')
    form_class = ProductCategoryAdminUpdateForm


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    success_url = reverse_lazy('admin_panel:category_list')
    form_class = ProductCategoryAdminUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Админка/редактирование категории товара'
        return context


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_panel:category_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda x: x.is_superuser)
def category_products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)

    context = {
        'page_title': 'Админка/товары категории',
        'category': category,
        'object_list': category.product_set.all()
    }

    return render(request, 'adminapp/product_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_create(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': pk}))
    else:
        form = ProductAdminUpdateForm(initial={'category': category})

    context = {
        'page_title': 'Админка/новый товар',
        'form': form,
    }

    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': product.category.pk}))
    else:
        form = ProductAdminUpdateForm(instance=product)

    context = {
        'page_title': 'Админка/редактирование товара',
        'form': form,
        'object': product
    }

    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': product.category.pk}))
    elif request.method == 'GET':
        context = {
            'page_title': 'Админка/удаление продукта',
            'object': product,
        }
        return render(request, 'adminapp/product_delete.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Админка/Подробная информация'
        return context

backend/apps/authapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from backend.apps.authapp.forms import UserLoginForm, UserRegisterForm, UserUpdateForm
from django.contrib import auth


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Вход в систему',
        'form': form,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = UserRegisterForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }

    return render(request, 'authapp/register.html', context)


def update(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:update'))
    else:
        form = UserUpdateForm(instance=request.user)

    context = {
        'page_title': 'редактирование профиля',
        'form': form
    }

    return render(request, 'authapp/update.html', context)

backend/apps/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from backend.apps.mainapp.views import get_basket
from backend.apps.basketapp.models import Basket
from backend.apps.mainapp.models import Product


@login_required
def index(request):
    context = {
        'page_title': 'Корзина',
        'basket': get_basket(request),
    }
    return render(request, 'basketapp/basket.html', context)


@login_required
def basket_add(request, pk):
    product = get_object_or_404(Product, pk=pk)
    basket_item = Basket.objects.filter(user=request.user,
                                        product=product).first()
    if basket_item:
        basket_item.quantity += 1
        basket_item.save()
    else:
        Basket.objects.create(user=request.user,
                              product=product,
                              quantity=1)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_delete(request, pk):
    get_object_or_404(Basket, pk=pk).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

backend/apps/mainapp/views.py
import json
from django.shortcuts import render, get_object_or_404

from backend.apps.mainapp.models import Product, ProductCategory


# Create your views here.
def get_products_menu():
    return ProductCategory.objects.all()


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')
    else:
        return []


def main(request):
    new_products = Product.objects.all()[:3]

    context = {
        'page_title': 'Магазин',
        'new_products': new_products
    }
    return render(request, 'mainapp/index.html', context)


def catalog(request):
    catalog_products = Product.objects.all()[:8]

    context = {
        'page_title': 'Каталог',
        'products_menu': get_products_menu(),
        'catalog_products': catalog_products,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/catalog.html', context)


def contacts(request):
    context = {
        'page_title': 'Контакты',
    }
    return render(request, 'mainapp/contacts.html', context)


def product(request, pk):
    context = {
        'page_title': 'Страница товара',
        'product': get_object_or_404(Product, pk=pk),
        'products_menu': get_products_menu(),
        'category': Product.category,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/product.html', context)

backend/apps/orderapp/views.py
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from backend.apps.basketapp.models import Basket
from backend.apps.orderapp.forms import OrderItemForm
from backend.apps.orderapp.models import Order, OrderItem


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem,
                                             form=OrderItemForm,
                                             extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.get_items(self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem,
                                                     form=OrderItemForm,
                                                     extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                basket_items.delete()
            else:
                formset = OrderFormSet()

        data['order_items'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if order_items.is_valid():
                order_items.instance = self.object
                order_items.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['page_title'] = 'Заказ/Просмотр'
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('order:orders_list'))


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['order_items'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            data['order_items'] = OrderFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']

        with transaction.atomic():
            self.object = form.save()
            if order_items.is_valid():
                order_items.instance = self.object
                order_items.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('order:orders_list')

backend/templates/adminapp/admin_panel.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Админка</h2>
    <div class="admin_panel_content">
        <p class="greeting">Добро пожаловать в панель администратора, {{ user.first_name }}</p>
    </div>
    <div class="admin_button_panel">
        <a class="button" href="{% url 'admin_panel:user_list' %}">пользователи</a>
        <a class="button" href="{% url 'admin_panel:category_list' %}">категории</a>
    </div>
{% endblock %}

backend/templates/adminapp/category_delete.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Уверены, что хотите удалить категорию {{ object.name }}?</h2>
    <form method="post">
        {% csrf_token %}
        <div class="admin_button_panel">
            <input class="button" type="submit" value="удалить">
            <input class="button" type="button" value="отмена" onclick="location.href='{% url 'admin_panel:category_list' %}'">
        </div>
    </form>
{% endblock %}

backend/templates/adminapp/category_form.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Редактирование категории</h2>
    <div class="login">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="button form-control" type="submit" value="сохранить">
            <input class="button" type="button" value="отмена" onclick="location.href='{% url 'admin_panel:category_list' %}'">
        </form>
    </div>
{% endblock %}

backend/templates/adminapp/category_list.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Список категорий</h2>
    <div class="admin_panel_content">
        <div class="record_box">
            {% for object in object_list %}
                <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                    <div class="category_name">{{ object.name|title }}</div>
                    <div class="category_desc">{{ object.description }}</div>
                    <div class="category_actions">
                        <a class="button" href="{% url 'admin_panel:category_products' object.pk %}">товары категории</a>
                        <a class="button" href="{% url 'admin_panel:category_update' object.pk %}">редактировать</a>
                        <a class="button" href="{% url 'admin_panel:category_delete' object.pk %}">удалить</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="admin_button_panel">
        <a class="button" href="#">новая категория</a>
    </div>
{% endblock %}

backend/templates/adminapp/product_delete.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Уверены, что хотите удалить продукт <b>{{ object.name }}</b>?</h2>
    <form method="post">
        {% csrf_token %}
        <div class="admin_button_panel">
            <input class="button" type="submit" value="удалить">
            <input class="button" type="button" value="отмена" onclick="location.href='{% url 'admin_panel:category_list' %}'">
        </div>
    </form>
{% endblock %}

backend/templates/adminapp/product_detail.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <div class="product_detail_box">
        <div class="product_detail_left_side">
            <div class="product_detail_img">
                <img src="/media/{{ object.image|default:'prod_images/default.jpg' }}" alt="{{ object.name }}">
            </div>
            <div class="product_detail_summary">
                <p><b>цена: </b>{{ object.price }} руб</p>
                <p><b>количество: </b>{{ object.quantity }}</p>
                <p><b>в каталоге: </b>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            </div>
            <div class="product_detail_button">
                <a class="button" href="{% url 'admin_panel:product_update' object.pk %}">редактировать</a>
                <a class="button" href="{% url 'admin_panel:product_delete' object.pk %}">удалить</a>
                <a class="button" href="{% url 'admin_panel:category_products' object.category.pk %}">назад</a>
            </div>
        </div>
        <div class="product_detail_right_side">
            <div class="product_detail_name">
                <p>{{ object.category.name|title }} / {{ object.name|title }}</p>
            </div>
            <div class="product_detail_short_desc">
                <p class="product_detail_desc_title">Краткая информация</p>
                <p>{{ object.short_desc }}</p>
            </div>
            <div class="product_detail_full_desc">
                <p class="product_detail_desc_title">Подробная информация</p>
                <p>{{ object.description }}</p>
            </div>
        </div>
    </div>
{% endblock %}

backend/templates/adminapp/product_list.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Список продуктов категории {{ category.name }}</h2>
    <div class="admin_panel_content">
        <div class="record_box">
            {% for item in object_list %}
                <div class="product_record {% if not item.is_active %}not_active{% endif %}">
                    <div class="product_record_img">
                    <img src="/media/{{ item.image|default:'products_images/default.jpg' }}" alt="{{ item.name }}">
                    </div>
                    <div class="product_record_name record_center">{{ item.name|title }}</div>
                    <div class="product_record_summary record_center">
                        <p><b>цена: </b>{{ item.price }} руб<br>
                            <b>количество: </b>{{ item.quantity }}</p>
                    </div>

                    <div class="product_record_desc record_center">
                        {{ item.short_desc|title }}
                    </div>
                    <div class="record_button_panel">
                        <a class="button" href="{% url 'admin_panel:product_read' item.pk %}">подробнее</a>
                        <a class="button" href="{% url 'admin_panel:product_update' item.pk %}">редактировать</a>
                        <a class="button" href="{% url 'admin_panel:product_delete' item.pk %}">удалить</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="admin_button_panel">
        <a class="button" href="{% url 'admin_panel:product_create' category.pk %}">новый продукт</a>
    </div>
{% endblock %}

backend/templates/adminapp/product_update.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <div class="admin_panel_content">
        <div class="product_detail_edit_box">
            <div class="product_detail_edit_left">
                <div class="product_detail_img">
                    <img src="/media/{{ object.image|default:'prod_images/default.jpg' }}" alt="{{ object.name }}">
                </div>
            </div>

            <div class="product_detail_edit_right">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="button form-control" type="submit" value="сохранить">
                    <input class="button" type="button" value="отмена" onclick="location.href='{% url 'admin_panel:category_list' %}'">
                </form>
            </div>
        </div>
    </div>
    <div class="admin_button_panel">
        <a class="button" href="{% url 'admin_panel:user_list' %}">пользователи</a>
        <a class="button" href="{% url 'admin_panel:category_list' %}">категории</a>
    </div>
{% endblock %}

backend/templates/adminapp/productcategory_list.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Список категорий</h2>
    <div class="admin_panel_content">
        <div class="record_box">
            {% for object in object_list %}
                <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                    <div class="category_name">{{ object.name|title }}</div>
                    <div class="category_desc">{{ object.description }}</div>
                    <div class="category_actions">
                        <a class="button" href="#">товары категории</a>
                        <a class="button" href="#">редактировать</a>
                        <a class="button" href="#">удалить</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="admin_button_panel">
        <a class="button" href="#">новая категория</a>
    </div>
{% endblock %}

backend/templates/adminapp/user_delete.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Уверены, что хотите удалить пользователя {{ object.username }}
        {% if object.first_name %}
            ({{ object.first_name|title}}
            {% if object.last_name %}
                {{ object.last_name|title}}
            {% endif %})
        {% endif %}?
    </h2>

    <div>
        <form method="post">
            {% csrf_token %}
            <div class="admin_button_panel">
                <input class="button" type="submit" value="удалить">
                <input class="button" type="button" value="отмена" onclick="location.href='{% url 'admin_panel:user_list' %}'">
            </div>
        </form>
    </div>
{% endblock %}

backend/templates/adminapp/user_list.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>Список пользователей</h2>
    <div class="admin_panel_content">
        <div class="record_box">
            {% for object in object_list %}
                <div class="record">
                    <div>
                        <div class="user_avatar">
                            <img src="/media/{{ object.avatar|default:'user_avatars/default.jpg' }}" alt="{{ object.username }}">
                        </div>
                        <div {% if object.is_superuser %}
                            class="user_admin_role"
                            {% else %}
                            class="user_role"
                        {% endif %}>
                            {% if object.is_superuser %}
                                Администратор
                            {% else %}
                                Пользователь
                            {% endif %}
                        </div>
                    </div>
                    <div class="user_name">
                        <p><strong>{{ object.username }}</strong></p>
                        <p>
                            {% if object.first_name %}
                                {{ object.first_name|title }}
                                {% if object.last_name %}
                                    <br>{{ object.last_name|title }}
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                    <div class="user_data">Возраст:<br>{{ object.age }}</div>
                    <div class="user_data">Адрес почты:<br>{{ object.email }}</div>
                    <div class="user_data">Последний вход:<br>{{ object.last_login }}</div>
                    <div class="record_button_panel">
                        <a class="button" href="{% url 'admin_panel:user_update' object.pk %}">редактировать</a>
                        <a class="button" href="{% url 'admin_panel:user_delete' object.pk %}">удалить</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="admin_button_panel">
        <a class="button" href="{% url 'admin_panel:user_create' %}">добавить пользователя</a>
    </div>
{% endblock %}

backend/templates/adminapp/user_update.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="button form-control" type="submit" value="сохранить">
            <input class="button" type="button" value="отмена" onclick="location.href='{% url 'admin_panel:user_list' %}'">
        </form>
    </div>
{% endblock %}