backend/apps/adminapp/urls.py
from django.urls import re_path
import backend.apps.adminapp.views as admin

app_name = 'admin'

urlpatterns = [
    re_path(r'^$', admin.index, name='index'),

    re_path(r'^user_list/$', admin.user_list, name='user_list'),
    re_path(r'^user/create/$', admin.user_create, name='user_create'),
    re_path(r'^user/update/(?P<pk>\d+)/$', admin.user_update, name='user_update'),
    re_path(r'^user/delete/(?P<pk>\d+)/$', admin.user_delete, name='user_delete'),

    re_path(r'^category/list/$', admin.category_list, name='category_list'),
    re_path(r'^category/create/$', admin.CategoryCreateView.as_view(), name='category_create'),
    re_path(r'^category/update/(?P<pk>\d+)/$', admin.CategoryUpdateView.as_view(), name='category_update'),
    re_path(r'^category/delete/(?P<pk>\d+)/$', admin.CategoryDeleteView.as_view(), name='category_delete'),
    re_path(r'^category/products/(?P<pk>\d+)/$', admin.category_products, name='category_products'),

    re_path(r'^product/create/(?P<pk>\d+)/$', admin.product_create, name='product_create'),
    re_path(r'^product/read/(?P<pk>\d+)/$', admin.ProductDetailView.as_view(), name='product_read'),
    re_path(r'^product/update/(?P<pk>\d+)/$', admin.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', admin.product_delete, name='product_delete'),
]

backend/apps/authapp/urls.py
from django.urls import re_path
import backend.apps.authapp.views as auth

app_name = 'auth'

urlpatterns = [
    re_path(r'^login/$', auth.login, name='login'),
    re_path(r'^logout/$', auth.logout, name='logout'),
    re_path(r'^register/$', auth.register, name='register'),
    re_path(r'^update/$', auth.update, name='update'),
]

backend/apps/basketapp/urls.py
from django.urls import re_path
import backend.apps.basketapp.views as basket

app_name = 'basket'

urlpatterns = [
    re_path(r'^$', basket.index, name='index'),
    re_path(r'add/(?P<pk>\d+)/', basket.basket_add, name='add'),
    re_path(r'delete/(?P<pk>\d+)/', basket.basket_delete, name='delete'),
]

backend/apps/mainapp/urls.py
from django.urls import re_path
import backend.apps.mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.main, name='index'),
    re_path(r'^catalog/$', mainapp.catalog, name='catalog'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^contacts/$', mainapp.contacts, name='contacts'),
]

shop_it_trade/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'^', include('backend.apps.mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('backend.apps.authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('backend.apps.basketapp.urls', namespace='basket')),
    re_path(r'^admin_panel/', include('backend.apps.adminapp.urls', namespace='admin_panel')),
    re_path(r'^order/', include('backend.apps.orderapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/apps/adminapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import forms, HiddenInput, ModelForm

from backend.apps.mainapp.models import ProductCategory, Product
from backend.apps.authapp.models import User


class UserAdminCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'password1',
                  'password2',
                  'email',
                  'age',
                  'avatar')

    def __init__(self, *args, **kwargs):
        super(UserAdminCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data


class UserAdminUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'password',
                  'email',
                  'age',
                  'avatar',
                  'is_superuser',
                  'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды")
        return data


class ProductCategoryAdminUpdateForm(ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductAdminUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

backend/apps/orderapp/forms.py
from django import forms
from backend.apps.orderapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

backend/apps/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from backend.apps.adminapp.forms import UserAdminCreateForm, UserAdminUpdateForm, ProductCategoryAdminUpdateForm, \
    ProductAdminUpdateForm
from backend.apps.authapp.models import User
from backend.apps.mainapp.models import ProductCategory, Product


def index(request):
    context = {
        'page_title': 'Админка',
    }
    return render(request, 'adminapp/admin_panel.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_list(request):
    object_list = User.objects.all()[:3]

    context = {
        'page_title': 'Админка/пользователи',
        'object_list': object_list
    }
    return render(request, 'adminapp/user_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_create(request):
    if request.method == 'POST':
        form = UserAdminCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:index'))
    else:
        form = UserAdminCreateForm()

    context = {
        'page_title': 'Админка/новый пользователь',
        'form': form
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_update(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = UserAdminUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:index'))
    else:
        form = UserAdminUpdateForm(instance=user)

    context = {
        'page_title': 'Админка/редактирование пользователя',
        'form': form
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_delete(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin_panel:index'))
    elif request.method == 'GET':
        context = {
            'page_title': 'Админка/удаление пользователя',
            'object': user,
        }
        return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda x: x.is_superuser)
def category_list(request):
    object_list = ProductCategory.objects.all()

    context = {
        'page_title': 'Админка/категории',
        'object_list': object_list,
    }

    return render(request, 'adminapp/category_list.html', context)


class CategoryCreateView(CreateView):
    model = ProductCategory
    success_url = reverse_lazy('admin_panel:category_list')
    form_class = ProductCategoryAdminUpdateForm


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    success_url = reverse_lazy('admin_panel:category_list')
    form_class = ProductCategoryAdminUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Админка/редактирование категории товара'
        return context


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_panel:category_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda x: x.is_superuser)
def category_products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)

    context = {
        'page_title': 'Админка/товары категории',
        'category': category,
        'object_list': category.product_set.all()
    }

    return render(request, 'adminapp/product_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_create(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': pk}))
    else:
        form = ProductAdminUpdateForm(initial={'category': category})

    context = {
        'page_title': 'Админка/новый товар',
        'form': form,
    }

    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': product.category.pk}))
    else:
        form = ProductAdminUpdateForm(instance=product)

    context = {
        'page_title': 'Админка/редактирование товара',
        'form': form,
        'object': product
    }

    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': product.category.pk}))
    elif request.method == 'GET':
        context = {
            'page_title': 'Админка/удаление продукта',
            'object': product,
        }
        return render(request, 'adminapp/product_delete.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Админка/Подробная информация'
        return context

backend/apps/authapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from backend.apps.authapp.forms import UserLoginForm, UserRegisterForm, UserUpdateForm
from django.contrib import auth


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Вход в систему',
        'form': form,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = UserRegisterForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }

    return render(request, 'authapp/register.html', context)


def update(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:update'))
    else:
        form = UserUpdateForm(instance=request.user)

    context = {
        'page_title': 'редактирование профиля',
        'form': form
    }

    return render(request, 'authapp/update.html', context)

backend/apps/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from backend.apps.mainapp.views import get_basket
from backend.apps.basketapp.models import Basket
from backend.apps.mainapp.models import Product


@login_required
def index(request):
    context = {
        'page_title': 'Корзина',
        'basket': get_basket(request),
    }
    return render(request, 'basketapp/basket.html', context)


@login_required
def basket_add(request, pk):
    product = get_object_or_404(Product, pk=pk)
    basket_item = Basket.objects.filter(user=request.user,
                                        product=product).first()
    if basket_item:
        basket_item.quantity += 1
        basket_item.save()
    else:
        Basket.objects.create(user=request.user,
                              product=product,
                              quantity=1)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_delete(request, pk):
    get_object_or_404(Basket, pk=pk).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

backend/apps/mainapp/views.py
import json
from django.shortcuts import render, get_object_or_404

from backend.apps.mainapp.models import Product, ProductCategory


# Create your views here.
def get_products_menu():
    return ProductCategory.objects.all()


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')
    else:
        return []


def main(request):
    new_products = Product.objects.all()[:3]

    context = {
        'page_title': 'Магазин',
        'new_products': new_products
    }
    return render(request, 'mainapp/index.html', context)


def catalog(request):
    catalog_products = Product.objects.all()[:8]

    context = {
        'page_title': 'Каталог',
        'products_menu': get_products_menu(),
        'catalog_products': catalog_products,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/catalog.html', context)


def contacts(request):
    context = {
        'page_title': 'Контакты',
    }
    return render(request, 'mainapp/contacts.html', context)


def product(request, pk):
    context = {
        'page_title': 'Страница товара',
        'product': get_object_or_404(Product, pk=pk),
        'products_menu': get_products_menu(),
        'category': Product.category,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/product.html', context)

backend/templates/mainapp/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>
            {{ page_title|title }}
        </title>
    {% endblock %}

    {% block css %}
        <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" >
    {% endblock %}

    {% block favicon %}
        <link href="{% static 'img/favicon.ico' %}" type="image/x-icon" rel="icon" />
        <link href="{% static 'img/favicon.ico' %}" type="image/x-icon" rel="shortcut icon" />
    {% endblock %}
</head>

<body>
<div class='container'>
    {% block site_name %}
        <div class="header">
            <div class="logo">
                <img src="{% static 'img/logo.png' %}" alt="">
            </div>
            <div class="site_name">
                <h1>Интернет-магазин IT-trade</h1>
            </div>
            {% include 'mainapp/includes/inc__main_menu.html' %}
        </div>
    {% endblock %}

    <div class="content">
        {% block page_content %}
        {% endblock %}
    </div>

    {% block footer %}
        <div class="footer">
            &copy; 2018-{% now "Y" %} «Все права защищены». Сегодня {% now "d/m/Y" %}
        </div>
    {% endblock %}
</div>
</body>

</html>

backend/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block page_content %}
    <h2>Каталог товаров</h2>
    <div class="catalog_product_box">
        {% for item in catalog_products %}
        <div class="catalog_product" style="background-image: url(/media/{{ item.image }})">
            <a href="{% url 'main:product' item.pk %}">
                <div class="catalog_product_content">
                    <h4>{{ item.name }}</h4>
                    <p>{{ item.short_desc }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
{% endblock %}

backend/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}

{% block page_content %}
    <h2>Контактная информация</h2>
    <div class="contact_box">
        <div class="contact_left_side">
            <p>
                <script async="" charset="utf-8"
                        src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ae812fde5dbc0b531ada14d192089af3646d0d3611d0f6e630deb308b8f30cbdd&amp;width=500&amp;height=470&amp;lang=ru_RU&amp;scroll=true"
                        type="text/javascript"></script>
            </p>
        </div>
        <div class="contact_right_side">
            <p>Адрес: г.Санкт-Петербург, ул. Название улицы, д.345</p>
            <p>Телефон: 8(987)654-32-10</p>
            <p>Email: <a href="mailto:info@it-trade.ru">info@it-trade.ru</a></p>
            <hr>
            <div>
                <h4>Напишите нам</h4>
                <form action="">
                    <fieldset>
                        <input class="contact_oneline_text" placeholder="Имя" size="60" type="text"><br>
                        <p></p>
                        <input class="contact_oneline_text" placeholder="Email" size="60" type="text"><br>
                        <p></p>
                        <input class="contact_oneline_text" placeholder="Тема сообщения" size="60" type="text"><br>
                        <p></p>
                        <input class="contact_bigline_text" placeholder="Текст сообщения" size="60" type="text"
                               style="height: 100px"><br>
                        <p></p>
                        <div class="contact_form_buttons">
                            <input type="reset" value="Очистить">
                            <input type="button" value="Отправить">
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

backend/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block page_content %}
    <h2>Уважаемые покупатели!</h2>
    <p class="greeting">Мы рады приветствовать вас в нашем интернет-магазине. В каталоге вы сможете
        познакомиться с имеющимся у нас товаром и уточнить о его налиции на нашем складе.
        В разделе контакты размещена вся необходимая контактная информация: адрес, телефон,
        и схема проезда.</p>
    <h4>Посление поступления</h4>
    <div class="new_products_box">
    {% for item in new_products %}
        <div>
            <a class="new_products_link" href="#">
                <div class="new_product">
                    <h4>{{ item.name }}</h4>
                    <p class="description_short">{{ item.short_desc }}</p>
                    <div class="new_products_img" style="background-image: url(/media/{{ item.image }})">
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
    </div>
{% endblock %}

backend/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block page_content %}
    <div class="left_side">
        <img class="product_img" src="/media/{{ product.image }}">
        <p></p>
        <h2>Цена: {{ product.price }} руб</h2>
        <p></p>
        <h4>Кол-во на складе: {{ product.quantity }} шт.</h4>
        <p></p>
        <a class="red_button" href="{% url 'basket:add' product.pk %}">
            <div class="red_button">купить</div>
        </a>
    </div>
    <div class="right_side">
        <h1>{{ product.name }}</h1>
        <p class="product_full_info" style="text-align: justify;">{{ product.description }}</p>
    </div>


{% endblock %}