backend/apps/adminapp/urls.py
from django.urls import re_path
import backend.apps.adminapp.views as admin

app_name = 'admin'

urlpatterns = [
    re_path(r'^$', admin.index, name='index'),

    re_path(r'^user_list/$', admin.user_list, name='user_list'),
    re_path(r'^user/create/$', admin.user_create, name='user_create'),
    re_path(r'^user/update/(?P<pk>\d+)/$', admin.user_update, name='user_update'),
    re_path(r'^user/delete/(?P<pk>\d+)/$', admin.user_delete, name='user_delete'),

    re_path(r'^category/list/$', admin.category_list, name='category_list'),
    re_path(r'^category/create/$', admin.CategoryCreateView.as_view(), name='category_create'),
    re_path(r'^category/update/(?P<pk>\d+)/$', admin.CategoryUpdateView.as_view(), name='category_update'),
    re_path(r'^category/delete/(?P<pk>\d+)/$', admin.CategoryDeleteView.as_view(), name='category_delete'),
    re_path(r'^category/products/(?P<pk>\d+)/$', admin.category_products, name='category_products'),

    re_path(r'^product/create/(?P<pk>\d+)/$', admin.product_create, name='product_create'),
    re_path(r'^product/read/(?P<pk>\d+)/$', admin.ProductDetailView.as_view(), name='product_read'),
    re_path(r'^product/update/(?P<pk>\d+)/$', admin.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', admin.product_delete, name='product_delete'),
]

backend/apps/authapp/urls.py
from django.urls import re_path
import backend.apps.authapp.views as auth

app_name = 'auth'

urlpatterns = [
    re_path(r'^login/$', auth.login, name='login'),
    re_path(r'^logout/$', auth.logout, name='logout'),
    re_path(r'^register/$', auth.register, name='register'),
    re_path(r'^update/$', auth.update, name='update'),
]

backend/apps/mainapp/urls.py
from django.urls import re_path
import backend.apps.mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.main, name='index'),
    re_path(r'^catalog/$', mainapp.catalog, name='catalog'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    re_path(r'^contacts/$', mainapp.contacts, name='contacts'),
]

backend/apps/orderapp/urls.py
from django.urls import re_path
import backend.apps.orderapp.views as order

app_name = 'order'

urlpatterns = [
    re_path(r'^$', order.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', order.order_forming_complete, name='order_forming_complete'),

    re_path(r'^create/$', order.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', order.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', order.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', order.OrderDelete.as_view(), name='order_delete'),

]

shop_it_trade/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'^', include('backend.apps.mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('backend.apps.authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('backend.apps.basketapp.urls', namespace='basket')),
    re_path(r'^admin_panel/', include('backend.apps.adminapp.urls', namespace='admin_panel')),
    re_path(r'^order/', include('backend.apps.orderapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/apps/orderapp/models.py
from django.db import models

from django.conf import settings
from backend.apps.mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.order_items.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.order_items.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.order_items.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.order_items.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name="order_items",
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

backend/apps/orderapp/forms.py
from django import forms
from backend.apps.orderapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

backend/apps/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from backend.apps.adminapp.forms import UserAdminCreateForm, UserAdminUpdateForm, ProductCategoryAdminUpdateForm, \
    ProductAdminUpdateForm
from backend.apps.authapp.models import User
from backend.apps.mainapp.models import ProductCategory, Product


def index(request):
    context = {
        'page_title': 'Админка',
    }
    return render(request, 'adminapp/admin_panel.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_list(request):
    object_list = User.objects.all()[:3]

    context = {
        'page_title': 'Админка/пользователи',
        'object_list': object_list
    }
    return render(request, 'adminapp/user_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_create(request):
    if request.method == 'POST':
        form = UserAdminCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:index'))
    else:
        form = UserAdminCreateForm()

    context = {
        'page_title': 'Админка/новый пользователь',
        'form': form
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_update(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = UserAdminUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:index'))
    else:
        form = UserAdminUpdateForm(instance=user)

    context = {
        'page_title': 'Админка/редактирование пользователя',
        'form': form
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_delete(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin_panel:index'))
    elif request.method == 'GET':
        context = {
            'page_title': 'Админка/удаление пользователя',
            'object': user,
        }
        return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda x: x.is_superuser)
def category_list(request):
    object_list = ProductCategory.objects.all()

    context = {
        'page_title': 'Админка/категории',
        'object_list': object_list,
    }

    return render(request, 'adminapp/category_list.html', context)


class CategoryCreateView(CreateView):
    model = ProductCategory
    success_url = reverse_lazy('admin_panel:category_list')
    form_class = ProductCategoryAdminUpdateForm


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    success_url = reverse_lazy('admin_panel:category_list')
    form_class = ProductCategoryAdminUpdateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Админка/редактирование категории товара'
        return context


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_panel:category_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda x: x.is_superuser)
def category_products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)

    context = {
        'page_title': 'Админка/товары категории',
        'category': category,
        'object_list': category.product_set.all()
    }

    return render(request, 'adminapp/product_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_create(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': pk}))
    else:
        form = ProductAdminUpdateForm(initial={'category': category})

    context = {
        'page_title': 'Админка/новый товар',
        'form': form,
    }

    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': product.category.pk}))
    else:
        form = ProductAdminUpdateForm(instance=product)

    context = {
        'page_title': 'Админка/редактирование товара',
        'form': form,
        'object': product
    }

    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin_panel:category_products', kwargs={'pk': product.category.pk}))
    elif request.method == 'GET':
        context = {
            'page_title': 'Админка/удаление продукта',
            'object': product,
        }
        return render(request, 'adminapp/product_delete.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Админка/Подробная информация'
        return context

backend/apps/authapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from backend.apps.authapp.forms import UserLoginForm, UserRegisterForm, UserUpdateForm
from django.contrib import auth


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Вход в систему',
        'form': form,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = UserRegisterForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }

    return render(request, 'authapp/register.html', context)


def update(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:update'))
    else:
        form = UserUpdateForm(instance=request.user)

    context = {
        'page_title': 'редактирование профиля',
        'form': form
    }

    return render(request, 'authapp/update.html', context)

backend/apps/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from backend.apps.mainapp.views import get_basket
from backend.apps.basketapp.models import Basket
from backend.apps.mainapp.models import Product


@login_required
def index(request):
    context = {
        'page_title': 'Корзина',
        'basket': get_basket(request),
    }
    return render(request, 'basketapp/basket.html', context)


@login_required
def basket_add(request, pk):
    product = get_object_or_404(Product, pk=pk)
    basket_item = Basket.objects.filter(user=request.user,
                                        product=product).first()
    if basket_item:
        basket_item.quantity += 1
        basket_item.save()
    else:
        Basket.objects.create(user=request.user,
                              product=product,
                              quantity=1)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_delete(request, pk):
    get_object_or_404(Basket, pk=pk).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

backend/apps/mainapp/views.py
import json
from django.shortcuts import render, get_object_or_404

from backend.apps.mainapp.models import Product, ProductCategory


# Create your views here.
def get_products_menu():
    return ProductCategory.objects.all()


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')
    else:
        return []


def main(request):
    new_products = Product.objects.all()[:3]

    context = {
        'page_title': 'Магазин',
        'new_products': new_products
    }
    return render(request, 'mainapp/index.html', context)


def catalog(request):
    catalog_products = Product.objects.all()[:8]

    context = {
        'page_title': 'Каталог',
        'products_menu': get_products_menu(),
        'catalog_products': catalog_products,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/catalog.html', context)


def contacts(request):
    context = {
        'page_title': 'Контакты',
    }
    return render(request, 'mainapp/contacts.html', context)


def product(request, pk):
    context = {
        'page_title': 'Страница товара',
        'product': get_object_or_404(Product, pk=pk),
        'products_menu': get_products_menu(),
        'category': Product.category,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/product.html', context)

backend/templates/orderapp/order_delete.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
   <div class="category_delete">
       {% include 'orderapp/includes/inc_order_summary.html' %}
       <form action="{% url 'order:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <div class="order_button_panel">
               <h2>Уверены, что хотите удалить?</h2>
               <input class="button" type="submit" value="удалить">
               <input class="button" type="button" value="отмена" onclick="location.href='{% url 'order:orders_list' %}'">
           </div>
       </form>
   </div>
{% endblock %}

backend/templates/orderapp/order_detail.html
{% extends "mainapp/base.html" %}


{% block page_content %}
    <div class="order_box">
        <div class="order_detail">
            {% include 'orderapp/includes/inc_order_summary.html' %}
            {% for item in object.orderitems.select_related %}
                <div class="order_detail">
                    <img src="{{ item.product.image }}" alt="{{ item.product.short_desc }}">
                    <span class="category_name">
                        {{ item.product.category.name }}
                    </span>
                    <span class="product_name">{{ item.product.name }}</span>
                    <span class="product_price">{{ item.product.price }} руб.</span>
                    <span class="product_quantity">x {{ item.quantity }} шт.</span>
                    <span class="product_cost">= {{ item.get_product_cost }} руб.</span>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="order_button_panel">
        {% include 'orderapp/includes/inc_order_actions.html' %}
    </div>
{% endblock %}

backend/templates/orderapp/order_form.html
{% extends "mainapp/base.html" %}


{% block page_content %}
    <div class="order_box detail_border">
        {% include 'orderapp/includes/inc_order_summary.html' %}
        <div class="order_new_box detail_border">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <table>
                    {{ order_items.management_form }}
                    {% for form in order_items.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th >{{ field.label|capfirst }}</th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}
                        <tr>
                            {% for field in form.visible_fields %}
                                <td>
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
                                    {{ field }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            <div class="button_panel_center"><button type="submit" value="сохранить" class="button form-control">сохранить</button></div>
            </form>
        </div>
    </div>
    <div class="order_button_panel">
        {% include 'orderapp/includes/inc_order_actions.html' %}
    </div>
{% endblock %}

backend/templates/orderapp/order_list.html
{% extends 'mainapp/base.html' %}


{% block page_content %}
    <h2>
       Ваши заказы,
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
    </h2>
    <div class="order_box detail_border">
        <table class="table orders_list">
           <thead>
             <tr>
               <th>ID</th>
               <th>Создан</th>
               <th>Обновлен</th>
               <th>Статус</th>
             </tr>
           </thead>
           <tbody>
               {% for item in object_list %}
                   {% if item.is_active %}
                   <tr>
                       <td>{{ item.pk }}</td>
                       <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                       <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                       <td>{{ item.get_status_display }}</td>
                       <td><a class="button" href="{% url 'order:order_read' item.pk %}">посмотреть</a></td>
                       <td>
                           {% if item.status == 'FM' %}
                             <a  class="button" href="{% url 'order:order_update' item.pk %}">редактировать</a>
                           {% endif %}
                       </td>
                       <td>
                           {% if item.status == 'FM' %}
                             <a  class="button" href="{% url 'order:order_delete' item.pk %}">удалить</a>
                           {% endif %}
                       </td>
                   </tr>
                   {% endif %}
               {% endfor %}
           </tbody>
       </table>
    </div>
    <div class="order_button_panel">
        <a class="button" href="{% url 'main:index' %}">на главную</a>
        <a class="button" href="{% url 'order:order_create' %}">оформить заказ</a>
    </div>
{% endblock %}